[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "ffmpeg",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "fontconfig"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'build skipped'"]

[start]
cmd = "node server.mjs"
